# Generated by Django 5.0.6 on 2024-06-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('category', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('reviews', models.IntegerField(default=0)),
            ],
        ),
    ]
