# Generated by Django 5.0.6 on 2024-06-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crema',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Papa',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('porcion', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Pollo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('parte', models.CharField(max_length=100)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=255)),
                ('cubiertos', models.BooleanField(default=False)),
                ('pagoRealizado', models.BooleanField(default=False)),
                ('bebidas', models.ManyToManyField(blank=True, to='pedidos.bebida')),
                ('cremas', models.ManyToManyField(blank=True, to='pedidos.crema')),
                ('papas', models.ManyToManyField(blank=True, to='pedidos.papa')),
                ('pollos', models.ManyToManyField(blank=True, to='pedidos.pollo')),
            ],
        ),
    ]
